version: 2
project_name: kpv
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # removed ignore windows/arm64 rule to enable building for it
archives:
  - format: tar.gz
    # completely lowercased format
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - id: kpv
    file_name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    vendor: frostyeti
    homepage: https://github.com/frostyeti/kpv
    maintainer: frostyeti <frostyeti@users.noreply.github.com>
    description: KeePass Vault CLI
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
aurs:
  - name: kpv-bin
    homepage: https://github.com/frostyeti/kpv
    description: KeePass Vault CLI
    maintainer: frostyeti <frostyeti@users.noreply.github.com>
    license: MIT
brews:
  - name: kpv
    repository:
      owner: frostyeti
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/frostyeti/kpv
    description: KeePass Vault CLI
    license: MIT
chocolateys:
  - name: kpv
    owners: frostyeti
    title: kpv
    authors: frostyeti
    project_url: https://github.com/frostyeti/kpv
    description: KeePass Vault CLI
    tags: keepass vault cli
# Placeholder for AppImage
# appimages:
#   - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
dockers:
  - image_templates:
      - "ghcr.io/frostyeti/kpv:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'