version: 2
project_name: kpv
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - id: kpv
    file_name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    vendor: frostyeti
    homepage: https://github.com/frostyeti/kpv
    maintainer: frostyeti <frostyeti@users.noreply.github.com>
    description: KeePass Vault CLI
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
aurs:
  - name: kpv-bin
    homepage: https://github.com/frostyeti/kpv
    description: KeePass Vault CLI
    maintainers:
      - frostyeti <frostyeti@users.noreply.github.com>
    license: MIT
chocolateys:
  - name: kpv
    owners: frostyeti
    title: kpv
    authors: frostyeti
    project_url: https://github.com/frostyeti/kpv
    description: KeePass Vault CLI
    tags: keepass vault cli
    # skip_publish: true is for chocolatey, it means don't push to chocolatey.org. By default it doesn't anyway unless configured.
winget:
  - name: kpv
    publisher: frostyeti
    license: MIT
    short_description: KeePass Vault CLI
    homepage: https://github.com/frostyeti/kpv
    skip_upload: true
    repository:
      owner: frostyeti
      name: winget-pkgs
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: '{{ incpatch .Version }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
